# Generated by Django 4.1.3 on 2022-11-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y1', models.FloatField()),
                ('y2', models.FloatField()),
                ('type_name', models.CharField(max_length=64)),
                ('tags', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Grave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.figure')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.BinaryField()),
                ('author', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Skeleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.FloatField()),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.figure')),
                ('grave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.grave')),
            ],
        ),
        migrations.CreateModel(
            name='Skull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.figure')),
                ('skeleton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.skeleton')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
                ('location', models.CharField(max_length=64)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_ratio', models.FloatField()),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.figure')),
                ('grave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.grave')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('number', models.IntegerField()),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.publication')),
            ],
        ),
        migrations.CreateModel(
            name='GraveCrossSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.figure')),
                ('grave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graves.grave')),
            ],
        ),
        migrations.AddField(
            model_name='grave',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graves.site'),
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.figure')),
                ('grave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.grave')),
            ],
        ),
        migrations.AddField(
            model_name='figure',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.page'),
        ),
        migrations.CreateModel(
            name='Arrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.FloatField()),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.figure')),
                ('grave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graves.grave')),
            ],
        ),
    ]
