require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/kiosk_configs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # KioskConfig. As you add validations to KioskConfig, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      KioskConfig.create! valid_attributes
      get kiosk_configs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      kiosk_config = KioskConfig.create! valid_attributes
      get kiosk_config_url(kiosk_config)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_kiosk_config_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      kiosk_config = KioskConfig.create! valid_attributes
      get edit_kiosk_config_url(kiosk_config)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new KioskConfig" do
        expect {
          post kiosk_configs_url, params: { kiosk_config: valid_attributes }
        }.to change(KioskConfig, :count).by(1)
      end

      it "redirects to the created kiosk_config" do
        post kiosk_configs_url, params: { kiosk_config: valid_attributes }
        expect(response).to redirect_to(kiosk_config_url(KioskConfig.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new KioskConfig" do
        expect {
          post kiosk_configs_url, params: { kiosk_config: invalid_attributes }
        }.to change(KioskConfig, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post kiosk_configs_url, params: { kiosk_config: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested kiosk_config" do
        kiosk_config = KioskConfig.create! valid_attributes
        patch kiosk_config_url(kiosk_config), params: { kiosk_config: new_attributes }
        kiosk_config.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the kiosk_config" do
        kiosk_config = KioskConfig.create! valid_attributes
        patch kiosk_config_url(kiosk_config), params: { kiosk_config: new_attributes }
        kiosk_config.reload
        expect(response).to redirect_to(kiosk_config_url(kiosk_config))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        kiosk_config = KioskConfig.create! valid_attributes
        patch kiosk_config_url(kiosk_config), params: { kiosk_config: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested kiosk_config" do
      kiosk_config = KioskConfig.create! valid_attributes
      expect {
        delete kiosk_config_url(kiosk_config)
      }.to change(KioskConfig, :count).by(-1)
    end

    it "redirects to the kiosk_configs list" do
      kiosk_config = KioskConfig.create! valid_attributes
      delete kiosk_config_url(kiosk_config)
      expect(response).to redirect_to(kiosk_configs_url)
    end
  end
end
